version: "3.9"
services:
  root:
    image: "server_dsp"
    ports:
      - "10000:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf root
    networks:
      app_net:
        ipv4_address: 10.114.0.11
  
  l1:
    image: "server_dsp"
    ports:
      - "10001:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l1
    networks:
      app_net:
        ipv4_address: 10.114.0.4
  
  l2:
    image: "server_dsp"
    ports:
      - "10002:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l2
    networks:
      app_net:
        ipv4_address: 10.114.0.9

  l3:
    image: "server_dsp"
    ports:
      - "10003:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l3
    networks:
      app_net:
        ipv4_address: 10.114.0.8

  l4:
    image: "server_dsp"
    ports:
      - "10004:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l4
    networks:
      app_net:
        ipv4_address: 10.114.0.6

  l5:
    image: "server_dsp"
    ports:
      - "10005:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l5
    networks:
      app_net:
        ipv4_address: 10.114.0.3

  l6:
    image: "server_dsp"
    ports:
      - "10006:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l6
    networks:
      app_net:
        ipv4_address: 10.114.0.2

  l7:
    image: "server_dsp"
    ports:
      - "10007:53/udp"
    volumes:
      - ./testdata/nameserver:/nameserver/
    working_dir: /nameserver/
    command: -conf l7
    networks:
      app_net:
        ipv4_address: 10.114.0.10


  resolver:
    image: "resolver_dsp"
    ports:
      - "10009:53/udp"
    volumes:
      - ./testdata/resolver:/resolver/
    working_dir: /resolver/
    command: -config=./config.yml
    networks:
      app_net:
        ipv4_address: 10.114.0.7
    depends_on:
      - root

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "10.114.0.0/24"
        - subnet: "2001:3984:3989::/64"